# Generated by Django 4.0.2 on 2022-02-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
    ]
